/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.pas.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import com.pas.web.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-15-2013
 * 
 * XDoclet definition:
 * @struts.action path="/loginandlogout" name="userForm" scope="request"
 */
public class LoginandlogoutAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * 使用分派action往往需要自己重命名函数
	 * 该函数用户响应登录请求
	 */
	public ActionForward userlogin(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		
		return null;
	}
	
	/** 
	 * 使用分派action往往需要自己重命名函数
	 * 该函数用户响应退出请求
	 */
	public ActionForward userlogout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		
		return null;
	}
}