/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.pas.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;
import org.apache.struts.actions.DispatchAction;

/** 
 * MyEclipse Struts
 * Creation date: 10-16-2013
 * 
 * XDoclet definition:
 * @struts.action path="/register" name="userForm" parameter="type" scope="request"
 */
public class RegisterAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	/*
	 * execute默认
	 */
	public ActionForward register(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaActionForm userForm = (DynaActionForm) form;// TODO Auto-generated method stub
		//从动态表单中取出数据
		String id=userForm.get("userid").toString();
		String pwd=userForm.get("password").toString();
		String email=userForm.get("email").toString();
		
		System.out.println(id+pwd+email);
		mapping.findForward("ok");
		return null;
	}
}